### ISSUE TITLE
SPEAKER in use error

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/Adafruit_CircuitPython_CLUE#3]
I ran this:
```
from adafruit_clue import clue
clue.play_tone(880, 1)
```

and got this error:
```
Traceback (most recent call last):
  File "code.py", line 3, in <module>
  File "adafruit_clue.py", line 658, in play_tone
  File "adafruit_clue.py", line 691, in start_tone
  File "adafruit_clue.py", line 634, in _generate_sample
ValueError: SPEAKER in use
```

**Comment by kattni** [comment]
Verified. Looking into this now.
